CREATE TABLE `co2_statements` (
	`heating_period_id` text PRIMARY KEY NOT NULL,
	`method` text NOT NULL,
	`area_m2` real,
	`service_emissions_kg` real,
	`service_area_m2` real,
	`service_kg_per_m2` real,
	`service_landlord_permille` integer,
	`service_total_cents` integer,
	`service_landlord_cents` integer,
	`service_users_total_cents` integer,
	`service_users_total_approx` integer DEFAULT false NOT NULL,
	`service_units_count` integer,
	`service_cost_item_id` text,
	`service_self_landlord_cents` integer,
	`service_fuel_gross_cents` integer,
	`service_fuel_net_cents` integer,
	FOREIGN KEY (`heating_period_id`) REFERENCES `heating_periods`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`service_cost_item_id`) REFERENCES `cost_items`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "co2_statements_method_known" CHECK("method" IN ('serviceDeducted', 'serviceShown', 'selfAfterService', 'self')),
	CONSTRAINT "co2_statements_service_complete" CHECK("method" NOT IN ('serviceDeducted', 'serviceShown') OR ("service_users_total_cents" IS NOT NULL AND "service_landlord_cents" IS NOT NULL AND "service_units_count" IS NOT NULL)),
	CONSTRAINT "co2_statements_users_total_not_negative" CHECK("service_users_total_cents" >= 0),
	CONSTRAINT "co2_statements_landlord_not_negative" CHECK("service_landlord_cents" >= 0),
	CONSTRAINT "co2_statements_total_not_negative" CHECK("service_total_cents" >= 0),
	CONSTRAINT "co2_statements_self_landlord_not_negative" CHECK("service_self_landlord_cents" >= 0),
	CONSTRAINT "co2_statements_fuel_gross_not_negative" CHECK("service_fuel_gross_cents" >= 0),
	CONSTRAINT "co2_statements_fuel_net_not_negative" CHECK("service_fuel_net_cents" >= 0),
	CONSTRAINT "co2_statements_emissions_not_negative" CHECK("service_emissions_kg" >= 0),
	CONSTRAINT "co2_statements_kg_per_m2_not_negative" CHECK("service_kg_per_m2" >= 0),
	CONSTRAINT "co2_statements_permille_valid" CHECK("service_landlord_permille" BETWEEN 0 AND 1000),
	CONSTRAINT "co2_statements_units_positive" CHECK("service_units_count" > 0),
	CONSTRAINT "co2_statements_area_positive" CHECK("area_m2" > 0),
	CONSTRAINT "co2_statements_service_area_positive" CHECK("service_area_m2" > 0)
);
--> statement-breakpoint
CREATE TABLE `co2_tenant_reliefs` (
	`statement_id` text NOT NULL,
	`tenancy_id` text NOT NULL,
	`cents` integer NOT NULL,
	PRIMARY KEY(`statement_id`, `tenancy_id`),
	FOREIGN KEY (`statement_id`) REFERENCES `co2_statements`(`heating_period_id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`tenancy_id`) REFERENCES `tenancies`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "co2_tenant_reliefs_cents_not_negative" CHECK("cents" >= 0)
);
