PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_fuel_deliveries` (
	`id` text PRIMARY KEY NOT NULL,
	`plant_id` text NOT NULL,
	`label` text DEFAULT '' NOT NULL,
	`invoice_date` text,
	`delivered_at` text,
	`invoice_from` text,
	`invoice_to` text,
	`unit_id` text,
	`amount_cents` integer,
	`quantity` real,
	`quantity_unit` text,
	`energy_kwh` real,
	`gas_basis` text,
	`heating_value` real,
	`fuel_grade` text,
	`emissions_kg` real,
	`co2_cost_cents` integer,
	`emission_factor` real,
	`grid_fee_cents` integer,
	`bio_cost_cents` integer,
	`share_permille` real,
	`fixed_cents` integer,
	`estimated` integer DEFAULT false NOT NULL,
	`used_by_service` integer DEFAULT true NOT NULL,
	FOREIGN KEY (`plant_id`) REFERENCES `heating_plants`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`unit_id`) REFERENCES `units`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "fuel_deliveries_quantity_unit_known" CHECK("quantity_unit" IN ('l', 'kg', 'm3', 'kWh', 'srm')),
	CONSTRAINT "fuel_deliveries_gas_basis_known" CHECK("gas_basis" IN ('hs', 'hi')),
	CONSTRAINT "fuel_deliveries_fuel_grade_known" CHECK("fuel_grade" IN ('heatingOilEL', 'heavyFuelOil', 'naturalGasH', 'naturalGasL', 'lpg', 'coke', 'lignite', 'hardCoal', 'firewood', 'woodPellets', 'woodChips')),
	CONSTRAINT "fuel_deliveries_invoice_complete" CHECK(("invoice_from" IS NULL) = ("invoice_to" IS NULL)),
	CONSTRAINT "fuel_deliveries_invoice_from_valid" CHECK("invoice_from" IS NULL OR "invoice_from" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "fuel_deliveries_invoice_to_valid" CHECK("invoice_to" IS NULL OR "invoice_to" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "fuel_deliveries_invoice_date_valid" CHECK("invoice_date" IS NULL OR "invoice_date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "fuel_deliveries_delivered_at_valid" CHECK("delivered_at" IS NULL OR "delivered_at" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "fuel_deliveries_invoice_order_valid" CHECK("invoice_from" IS NULL OR "invoice_from" <= "invoice_to"),
	CONSTRAINT "fuel_deliveries_share_valid" CHECK("share_permille" BETWEEN 0 AND 1000),
	CONSTRAINT "fuel_deliveries_heating_value_positive" CHECK("heating_value" > 0),
	CONSTRAINT "fuel_deliveries_quantity_not_negative" CHECK("quantity" >= 0),
	CONSTRAINT "fuel_deliveries_energy_not_negative" CHECK("energy_kwh" >= 0),
	CONSTRAINT "fuel_deliveries_emissions_not_negative" CHECK("emissions_kg" >= 0),
	CONSTRAINT "fuel_deliveries_co2_not_negative" CHECK("co2_cost_cents" >= 0),
	CONSTRAINT "fuel_deliveries_factor_not_negative" CHECK("emission_factor" >= 0),
	CONSTRAINT "fuel_deliveries_fixed_not_negative" CHECK("fixed_cents" >= 0),
	CONSTRAINT "fuel_deliveries_grid_fee_not_negative" CHECK("grid_fee_cents" >= 0),
	CONSTRAINT "fuel_deliveries_bio_not_negative" CHECK("bio_cost_cents" >= 0)
);
--> statement-breakpoint
INSERT INTO `__new_fuel_deliveries`("id", "plant_id", "label", "invoice_date", "delivered_at", "invoice_from", "invoice_to", "unit_id", "amount_cents", "quantity", "quantity_unit", "energy_kwh", "gas_basis", "heating_value", "fuel_grade", "emissions_kg", "co2_cost_cents", "emission_factor", "grid_fee_cents", "bio_cost_cents", "share_permille", "fixed_cents", "estimated", "used_by_service") SELECT "id", "plant_id", "label", "invoice_date", "delivered_at", "invoice_from", "invoice_to", "unit_id", "amount_cents", "quantity", "quantity_unit", "energy_kwh", "gas_basis", "heating_value", "fuel_grade", "emissions_kg", "co2_cost_cents", "emission_factor", "grid_fee_cents", "bio_cost_cents", "share_permille", "fixed_cents", "estimated", "used_by_service" FROM `fuel_deliveries`;--> statement-breakpoint
DROP TABLE `fuel_deliveries`;--> statement-breakpoint
ALTER TABLE `__new_fuel_deliveries` RENAME TO `fuel_deliveries`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_heating_plants` (
	`id` text PRIMARY KEY NOT NULL,
	`property_id` text NOT NULL,
	`name` text DEFAULT '' NOT NULL,
	`energy` text NOT NULL,
	`supply` text DEFAULT 'central' NOT NULL,
	`method` text DEFAULT 'manual' NOT NULL,
	`separate_settlement` integer,
	`devices_remote` text DEFAULT 'unknown' NOT NULL,
	`devices_installed_after_2021_12` text DEFAULT 'unknown' NOT NULL,
	`new_devices_install` text,
	`source` text DEFAULT 'building' NOT NULL,
	`capture_installed_on` text,
	`captured_on_2024_10_01` integer,
	`warm_rent_average_2022_2024` integer,
	`change_split` text DEFAULT 'degreeDays' NOT NULL,
	`period_start_month` integer,
	`units_limited` integer DEFAULT false NOT NULL,
	`non_residential` integer DEFAULT false NOT NULL,
	`restriction` text DEFAULT 'none' NOT NULL,
	`district_ets_new` integer DEFAULT false NOT NULL,
	`ends_on` text,
	`replaces_plant_id` text,
	`building_with` text,
	`takes_over_stock` integer,
	`hot_water` text DEFAULT 'combined' NOT NULL,
	`capture` text,
	`area_basis_heat` text DEFAULT 'area' NOT NULL,
	`heat_pump_installed_on` text,
	`heat_generation` text,
	`heat_pump_majority` text,
	FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "heating_plants_energy_known" CHECK("energy" IN ('gas', 'oil', 'lpg', 'pellets', 'wood', 'districtHeating', 'heatPump', 'electric', 'coal', 'other')),
	CONSTRAINT "heating_plants_supply_known" CHECK("supply" IN ('central', 'perUnit')),
	CONSTRAINT "heating_plants_method_known" CHECK("method" IN ('service', 'self', 'manual')),
	CONSTRAINT "heating_plants_devices_remote_known" CHECK("devices_remote" IN ('all', 'none', 'partial', 'unknown')),
	CONSTRAINT "heating_plants_devices_installed_known" CHECK("devices_installed_after_2021_12" IN ('all', 'some', 'none', 'unknown')),
	CONSTRAINT "heating_plants_new_devices_install_known" CHECK("new_devices_install" IN ('single', 'whole')),
	CONSTRAINT "heating_plants_source_known" CHECK("source" IN ('building', 'homeowners')),
	CONSTRAINT "heating_plants_change_split_known" CHECK("change_split" IN ('degreeDays', 'time')),
	CONSTRAINT "heating_plants_period_start_month_valid" CHECK("period_start_month" BETWEEN 1 AND 12),
	CONSTRAINT "heating_plants_source_method_valid" CHECK("source" <> 'homeowners' OR "method" = 'service'),
	CONSTRAINT "heating_plants_warm_rent_not_negative" CHECK("warm_rent_average_2022_2024" >= 0),
	CONSTRAINT "heating_plants_restriction_known" CHECK("restriction" IN ('none', 'building', 'supply', 'both')),
	CONSTRAINT "heating_plants_ets_district_valid" CHECK("district_ets_new" = 0 OR "energy" = 'districtHeating'),
	CONSTRAINT "heating_plants_hot_water_known" CHECK("hot_water" IN ('combined', 'separate', 'none')),
	CONSTRAINT "heating_plants_capture_known" CHECK("capture" IN ('heatMeter', 'hca', 'serviceValues')),
	CONSTRAINT "heating_plants_area_basis_heat_known" CHECK("area_basis_heat" IN ('area', 'heatedArea')),
	CONSTRAINT "heating_plants_self_capture_complete" CHECK("method" <> 'self' OR "capture" IS NOT NULL),
	CONSTRAINT "heating_plants_heat_generation_known" CHECK("heat_generation" IN ('single', 'mixed')),
	CONSTRAINT "heating_plants_heat_pump_majority_known" CHECK("heat_pump_majority" IN ('yes', 'no', 'unknown'))
);
--> statement-breakpoint
INSERT INTO `__new_heating_plants`("id", "property_id", "name", "energy", "supply", "method", "separate_settlement", "devices_remote", "devices_installed_after_2021_12", "new_devices_install", "source", "capture_installed_on", "captured_on_2024_10_01", "warm_rent_average_2022_2024", "change_split", "period_start_month", "units_limited", "non_residential", "restriction", "district_ets_new", "ends_on", "replaces_plant_id", "building_with", "takes_over_stock", "hot_water", "capture", "area_basis_heat", "heat_pump_installed_on", "heat_generation", "heat_pump_majority") SELECT "id", "property_id", "name", "energy", "supply", "method", "separate_settlement", "devices_remote", "devices_installed_after_2021_12", "new_devices_install", "source", "capture_installed_on", "captured_on_2024_10_01", "warm_rent_average_2022_2024", "change_split", "period_start_month", "units_limited", "non_residential", "restriction", "district_ets_new", "ends_on", "replaces_plant_id", "building_with", "takes_over_stock", "hot_water", "capture", "area_basis_heat", "heat_pump_installed_on", "heat_generation", "heat_pump_majority" FROM `heating_plants`;--> statement-breakpoint
DROP TABLE `heating_plants`;--> statement-breakpoint
ALTER TABLE `__new_heating_plants` RENAME TO `heating_plants`;